import Head from "next/head"
import { BiUserPlus, BiX, BiCheck } from "react-icons/bi"
import Table from "@/components/table"
import Form from "@/components/form"
import { useSelector, useDispatch  } from 'react-redux';
import { toggleChangeAction, deleteAction } from '../redux/reducer';
import { deleteUser, getUsers } from '../lib/helper';
import { useQueryClient } from 'react-query';
import { Text } from "@nextui-org/react";
 
export default function Home() {

  const visible = useSelector((state) => state.app.client.toggleForm)
  const deleteId = useSelector(state => state.app.client.deleteId)
  const queryclient = useQueryClient();

  const dispatch = useDispatch()

  const handler = () => {
    dispatch(toggleChangeAction())
  }
  
  const deletehandler =  async () => {
    if(deleteId){
      await deleteUser(deleteId);
      await queryclient.prefetchQuery('users', getUsers)
      await dispatch(deleteAction(null))
    }
  }

  const canclehandler = async () => {
    console.log("cancel")
    await dispatch(deleteAction(null))
  }

  return (
    <section>
      <Head>
        <title>Droame_Operator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className="py-5 px-1 ">
        {/* <h1 className="text-lg md:text-4xl text-center text-neutral-500 font-bold py-10">Customer Management</h1> */}

        <Text
        h1
        size={60}
        css={{
          textGradient: "45deg, $blue800 10%, $pink600 60%",
          textAlign: "center"
        }}
        weight="bold"
        >
          Customer Bookings
      </Text>
        
        <div className="container mx-auto flex justify-between mt-6 pt-10 border-t border-gray-300 py-5 ">
          <div className="left flex gap-3">
            <button onClick={handler} className="flex bg-indigo-500 transition text-white px-4 py-3 rounded-md shadow-lg shadow-indigo-500/50 hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-700 ">
              Add Customer <span className="pl-1"><BiUserPlus size={23}/></span>
            </button>
          </div>
          { deleteId ? DeleteComponent({ deletehandler, canclehandler }) : <></>}
        </div>   


        {/* Collapsable form */}       
        {visible ? <Form /> : <></>}     
        
          
        {/* Table */}
        <div className="container mx-auto">
          <Table className="container_table"></Table>
        </div> 
        
      </main>
    </section>
  )
}


function DeleteComponent({ deletehandler, canclehandler }){
  return (
    <div className='flex gap-5'>
        <button>Are you sure?</button>
        <button onClick={deletehandler} className='flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50'>
          Yes <span className='px-1'><BiX color='rgb(255 255 255)' size={25} /></span></button>
        <button onClick={canclehandler} className='flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-gree-500 hover:border-green-500 hover:text-gray-50'>
          No <span className='px-1'><BiCheck color='rgb(255 255 255)' size={25} /></span></button>
    </div>
  )
}
